version: "3.9"

services:
  backend:
    container_name: backend
    image: backend-dev
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    depends_on:
      - db
    ports:
      - 3001:3001
    env_file:
      - .env.docker
    working_dir: /app

  frontend:
    container_name: frontend
    image: frontend-dev
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    env_file:
      - .env.docker
    ports:
      - 3000:3000
    working_dir: /app

  db:
    image: postgres:13.4-alpine
    ports:
      - 5432:5432
    env_file:
      - .env.docker

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env.docker
    ports:
      - "3002:80"