version: "3.9"

services:
  backend:
    container_name: backend
    image: backend-dev
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 3001:3001
    working_dir: /app
  frontend:
    container_name: frontend
    image: frontend-dev
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 3000:3000
    working_dir: /app